### create user
###

POST http://localhost:4000/user-api/users
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "dateOfBirth": "1990-01-01",
    "mobileNumber": 1234567890
}
### get all users
###
GET http://localhost:4000/user-api/users

### get user by id
GET http://localhost:4000/user-api/users/69a684dc1b24909e4aee8d0c

###delete by user id
DELETE   http://localhost:4000/user-api/users/69a684dc1b24909e4aee8d0c

###activate user by id
PATCH  http://localhost:4000/user-api/users/69a684dc1b24909e4aee8d0c